---
  - name: Update & upgrade packages
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Download NodeJS version 14 with shell command
    shell: 'curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs'
    args:
      warn: false

  - name: Clone a bootcamp-app from github
    git:
      repo: https://github.com/benkatzav/bootcamp-app.git
      dest: /{{ app_dir }}/
      clone: yes
      update: yes

  - name: Creates the .env File
    template:
      src: ../templates/.env.j2
      dest: /{{ app_dir }}/.env

  - name: npm install
    npm:
      path: /{{ app_dir }}/

  - name: Install pm2
    npm:
      name: pm2
      global: yes

  - name: Delete old pm2 processes if exists
    shell: pm2 delete index
    ignore_errors: yes

  - name: Start Application
    shell: pm2 start src/index.js
    args:
      chdir: /{{ app_dir }}/

  - name: saving the state of pm2
    shell: pm2 save
    args:
      chdir: /{{ app_dir }}/

  - name: starting the state of pm2
    shell: pm2 startup && sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
    args:
      chdir: /{{ app_dir }}/

  - name: Initialize Tables in DB
    shell: npm run initdb
    async: 30
    poll: 0
    args:
      chdir: /{{ app_dir }}/
    run_once: true

  - name: reboot machine
    reboot:
